branch-defaults:
  default:
    environment: null
deploy:
  artifact: ./www/Archive.zip    
global:
  application_name: udagram-bombey-dev
  branch: null
  default_ec2_keyname: udagram-dev
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
